name: Deploy to GitHub pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate static VuePress files
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm i
    - run: npm run generate

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd ls -a
